<div class="sky-body">
    <div class="sky-body-header">
        <a href="/" class="sky-body-header-logo" style="background-image: url(<?php $V->LABEL('logo') ?>)"></a>
        <div class="sky-body-header-right"><?php $V->LABEL('auth') ?></div>
    </div>
    <div class="sky-body-menu">
        <?php $V->LABEL('menu') ?>
    </div>
    <div class="sky-body-content">
        <?php $V->LABEL('h1') ?>
        <?php $V->LABEL('main') ?>
    </div>
    <div class="sky-body-footer">
        <div class="sky-body-footer-copyright">&copy; Севастьянов Кирилл, 2013 г.</div>
        <?php $V->LABEL('footer') ?>
    </div>
</div>