<TITLE><?php echo $V->TITLE; ?></TITLE>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="<?php echo $V->BASE_HREF ?>" target="_self">
<META NAME="description" CONTENT="<?php echo $V->DESCRIPTION ?>">
<META NAME="keywords" CONTENT="<?php echo $V->KEYWORDS ?>">
<?php
    echo $V->THEME;

	FOREACH ($V->STYLESHEETS AS $STYLESHEET => $NULL) {
		echo '<LINK REL="stylesheet" TYPE="text/css" HREF="'.$STYLESHEET.'">';
	}

	FOREACH ($V->SCRIPTS AS $SCRIPT => $NULL) {
		echo '<SCRIPT SRC="'.$SCRIPT.'"></SCRIPT>';
	}

    echo $V->SKY_JS;